name = "analysis-tools"
type = "webpack"
account_id = "1c71f27d6fa097a1576b4ffab9186fa8"
workers_dev = false
route = "*analysis-tools.dev/*"
zone_id = "d0225a1c5a0f904f7483bbc781bfd807"

[site]
bucket = "./public"
entry-point = "workers-site"
